class CollectionItemKeys:
    NUMPLAYS = "numplays"
    COMMENT = "comment"
    THUMBNAILS = "thumbnails"
    STATUS = "status"
    OWN = "own"
    PREVOWNED = "prevowned"
    FORTRADE = "fortrade"
    WANT = "want"
    WANTTOPLAY = "wanttoplay"
    WANTTOBUY = "wanttobuy"
    WISHLIST = "wishlist"
    PREORDERED = "preordered"
    LASTMODIFIED = "lastmodified"
