class ThingItemKeys:
    NAME = "name"
    THUMBNAILS = "thumbnails"
    IMAGES = "images"
    DESCRIPTION = "description"
    PUBLISHED = "published"
    MIN_PLAYERS = "min_players"
    MAX_PLAYERS = "max_players"
    BOARDGAME_CATEGORIES = "boardgame_categories"
    BOARDGAME_IMPLEMENTATIONS = "boardgame_implementations"
    BOARDGAME_MECHANICS = "boardgame_mechanics"
    BOARDGAME_FAMILY = "boardgame_family"
    BOARDGAME_EXPANSIONS = "boardgame_expansions"
    BOARDGAME_VERSIONS = "boardgame_versions"
    DESIGNERS = "designers"
    ARTISTS = "artists"
    PUBLISHERS = "publishers"
    MARKETPLACE = "marketplace"


class CollectionItemKeys:
    NUMPLAYS = "numplays"
    COMMENT = "comment"
    THUMBNAILS = "thumbnails"
    STATUS = "status"
    OWN = "own"
    PREVOWNED = "prevowned"
    FORTRADE = "fortrade"
    WANT = "want"
    WANTTOPLAY = "wanttoplay"
    WANTTOBUY = "wanttobuy"
    WISHLIST = "wishlist"
    PREORDERED = "preordered"
    LASTMODIFIED = "lastmodified"
