"""bgg_integration

Revision ID: 330e37a60e0d
Revises: 
Create Date: 2021-08-22 12:53:18.585559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330e37a60e0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercollection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('updated', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usercollection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usercollection_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usercollection_updated'), ['updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_usercollection_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usercollection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usercollection_user_id'))
        batch_op.drop_index(batch_op.f('ix_usercollection_updated'))
        batch_op.drop_index(batch_op.f('ix_usercollection_id'))

    op.drop_table('usercollection')
    # ### end Alembic commands ###
